name: multi_agent_automl
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - django
      - openai
      - pytest
      - tqdm
      - loguru
      - instructor
      - python_dotenv
      - skops
      