name: CI Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false

      - name: Initialize Conda
        run: |
          conda init bash  # Initialize Conda for bash shell

      - name: Create and activate conda environment
        run: |
          conda env create -f environment.yml  # Create environment from environment.yml
          source ~/.bashrc  # Re-load shell configuration to ensure Conda is initialized
          conda activate multi_agent_automl  # Activate the environment
          conda info --envs  # Verify the environment is activated correctly

      - name: Verify pytest installation
        run: |
          pytest --version  # Check if pytest is installed and available

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q
